#!/usr/bin/env python3
"""Phase 6 Step 9: terminology cleanup v3 (three-pass).

v3 extends v2 with:
  - A NEW Pass 0 that fixes frankenwords left by v2 substitutions
    (e.g. "pre-registered the tuned ML baseline" from "pre-registered v10").
  - An extended Pass 1 that re-runs the v2 compound rules so captions
    regenerated by figure scripts after v2 are cleaned on this pass.
  - An extended Pass 2 that catches any collisions produced by the
    extended Pass 1.

Target surface is unchanged from v2:
    manuscripts/**/*.md
    figures/**/*.txt
    deliverables/lee_package_20260420/figures/**/*.txt

Explicitly NOT touched (same policy as v2):
    - CSV column names / JSON keys (machine contracts)
    - Notebook code cells
    - Log files
    - Script filenames
    - The phrase 'ship-if-better' itself

Writes TERMINOLOGY_CLEANUP_REPORT_V3.md.
"""
from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent.resolve()
os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------------------------------
# Pass 0: frankenword pre-clean (must run BEFORE Pass 1 so those bad phrases
# are not re-hit and compounded).
# ---------------------------------------------------------------------------
FRANKEN_SUBSTITUTIONS = [
    # "pre-registered v10 ..." -> v2 produced "pre-registered the tuned ML baseline"
    (r'\bpre-registered the tuned ML baseline\b', 'pre-registered ML baseline'),
    # "uncorrected v10 predictions" -> v2 produced "uncorrected the tuned ML baseline predictions"
    (r'\buncorrected the tuned ML baseline predictions\b',
     'uncorrected predictions'),
    (r'\buncorrected the tuned ML baseline prediction\b',
     'uncorrected prediction'),
    # "our v10 ..." -> "our the tuned ML baseline ..."
    (r'\bour the tuned ML baseline\b',     'our tuned ML baseline'),
    # "the v10 pipeline" -> "the the tuned ML pipeline" (v2 Pass 2 fixed
    # "the the"-only, but double-article through a different noun survives)
    (r'\bthe the tuned ML pipeline\b',     'the tuned ML pipeline'),
    # "a v10 ..." -> "a the tuned ML baseline ..."
    (r'\ba the tuned ML baseline\b',       'a tuned ML baseline'),
    (r'\ban the tuned ML baseline\b',      'a tuned ML baseline'),
    # "with v10 ..." -> "with the tuned ML baseline ..." (fine) but guard
    # against compound phrases
    (r'\bthe tuned ML baseline baseline\b', 'tuned ML baseline'),
]

# ---------------------------------------------------------------------------
# Pass 1: compound substitutions (same rule set as v2, longest-first).
# Re-running these is safe after Pass 0 stripped the frankenwords.
# ---------------------------------------------------------------------------
COMPOUND_SUBSTITUTIONS = [
    (r'\bv10 tuned pre\b',           'pre-correction tuned baseline'),
    (r'\bv10 tuned post\b',          'post-correction tuned baseline'),
    (r'\bv10_post[-\s]correction\b', 'post-correction'),
    (r'\bv10 post[-\s]correction\b', 'post-correction'),
    (r'\bv10 pre[-\s]registered\b',  'pre-registered'),
    (r'\bv10 pre[-\s]correction\b',  'pre-correction'),
    (r'\bv10 best\b',                'best tuned model'),
    (r'\bv10 RMSE\b',                'tuned RMSE'),
    (r'\bv10_pre\b',                 'pre-correction'),
    (r'\bv10_corrected\b',           'post-correction'),
    (r'\bv10_post\b',                'post-correction'),
    (r'\braw v10\b',                 'raw (uncorrected) tuned baseline'),
    (r'\bv10 pre\b',                 'pre-correction'),
    (r'\bv10 post\b',                'post-correction'),
    (r'\bv10 pipeline\b',            'the tuned ML pipeline'),
    (r'\bv10\b',                     'the tuned ML baseline'),
    (r'\bv9 finding\b',              'earlier finding'),
    (r'\bv9 empty\b',                'earlier empty'),
    (r'\bv9\b',                      'the previous iteration'),
    (r'\bPhase[- ]?G\.?\d+[a-z]?\b', 'the final phase'),
    (r'\bPhase[- ]?G\b',             'the final phase'),
    (r'\bPhase[- ]?\d+\.?\d*[a-z]?\b', 'the relevant phase'),
    (r'\bphase g\.?\d+[a-z]?\b',     'the final phase'),
    (r'\btwo-axis honesty bar\b',    'dual robustness check'),
    (r'\bno-degradation rule\b',     'no-regime-worsens requirement'),
    (r'\b"?ships A/B"?\b',           'accepts Form A or Form B'),
    (r'\b"?ships A"?\b',             'accepts Form A'),
    (r'\b"?ships B"?\b',             'accepts Form B'),
    (r'\bopx-tb\b',                  'the opx ML thermobarometer'),
    (r'\bopx_tb\b',                  'opx ML thermobarometer'),
]

# ---------------------------------------------------------------------------
# Pass 2: cosmetic fixups (v2 rules + v3 additions for new collisions).
# ---------------------------------------------------------------------------
COSMETIC_SUBSTITUTIONS = [
    (r'\bthe the tuned ML baseline\b',  'the tuned ML baseline'),
    (r'\bthe the tuned\b',              'the tuned'),
    (r'\bthe the final phase\b',        'the final phase'),
    (r'\bthe the relevant phase\b',     'the relevant phase'),
    (r'\bthe the previous iteration\b', 'the previous iteration'),
    (r'\bthe the\b',                    'the'),
    (r'\bpost-correction-correction\b', 'post-correction'),
    (r'\bpre-correction-correction\b',  'pre-correction'),
    (r'\bpre-correction-registered\b',  'pre-registered'),
    (r'\btuned ML baseline tuned pre-correction\b',  'pre-correction tuned baseline'),
    (r'\btuned ML baseline tuned post-correction\b', 'post-correction tuned baseline'),
    (r'\btuned ML baseline tuned (pre|post)-correction\b', r'\1-correction tuned baseline'),
    # v3-new: the Pass-1 hit "v10" -> "the tuned ML baseline" sometimes
    # produces "the tuned ML baseline post-correction" where cleaner prose
    # is "tuned ML baseline post-correction" (no definite article when
    # the phrase is adjectival).
    (r'\bthe tuned ML baseline post-correction\b', 'tuned ML baseline post-correction'),
    (r'\bthe tuned ML baseline pre-correction\b',  'tuned ML baseline pre-correction'),
    (r'\bthe tuned ML baseline tuned\b',           'tuned ML baseline'),
]

TARGETS = [
    (PROJECT_ROOT / 'manuscripts', '*.md'),
    (PROJECT_ROOT / 'figures', '*.txt'),
    (PROJECT_ROOT / 'deliverables' / 'lee_package_20260420' / 'figures', '*.txt'),
]

REPORT_PATH = PROJECT_ROOT / 'TERMINOLOGY_CLEANUP_REPORT_V3.md'


@dataclass
class Hit:
    path: Path
    pattern: str
    replacement: str
    count: int
    pass_num: int


def apply_subs(text: str, subs: list[tuple[str, str]]
               ) -> tuple[str, list[tuple[str, str, int]]]:
    records = []
    for pat, rep in subs:
        new_text, n = re.subn(pat, rep, text)
        if n:
            records.append((pat, rep, n))
            text = new_text
    return text, records


def main() -> int:
    hits: list[Hit] = []
    files_touched = 0
    for root, glob in TARGETS:
        if not root.exists():
            continue
        for p in root.rglob(glob):
            try:
                orig = p.read_text(encoding='utf-8')
            except UnicodeDecodeError:
                continue
            after0, recs0 = apply_subs(orig, FRANKEN_SUBSTITUTIONS)
            after1, recs1 = apply_subs(after0, COMPOUND_SUBSTITUTIONS)
            after2, recs2 = apply_subs(after1, COSMETIC_SUBSTITUTIONS)
            if after2 != orig:
                p.write_text(after2, encoding='utf-8')
                files_touched += 1
                for pat, rep, n in recs0:
                    hits.append(Hit(p, pat, rep, n, 0))
                for pat, rep, n in recs1:
                    hits.append(Hit(p, pat, rep, n, 1))
                for pat, rep, n in recs2:
                    hits.append(Hit(p, pat, rep, n, 2))

    lines = [
        '# Terminology cleanup report v3 (three-pass)',
        '',
        'Generated 2026-04-20 by `scripts/audits/terminology_cleanup_v3.py`.',
        '',
        '## Pass 0 rules (frankenword pre-clean, NEW in v3)',
        '',
    ]
    for pat, rep in FRANKEN_SUBSTITUTIONS:
        lines.append(f'- `{pat}` -> `{rep}`')
    lines.extend(['', '## Pass 1 rules (compound, longest-first)', ''])
    for pat, rep in COMPOUND_SUBSTITUTIONS:
        lines.append(f'- `{pat}` -> `{rep}`')
    lines.extend(['', '## Pass 2 rules (cosmetic fixups)', ''])
    for pat, rep in COSMETIC_SUBSTITUTIONS:
        lines.append(f'- `{pat}` -> `{rep}`')
    lines.extend(['', '## Targets', ''])
    for root, glob in TARGETS:
        try:
            rel = root.relative_to(PROJECT_ROOT)
            lines.append(f'- `{rel}/**/{glob}`')
        except ValueError:
            lines.append(f'- `{root}/**/{glob}`')
    lines.extend([
        '',
        '## Files modified',
        '',
        f'Total: {files_touched} files, {sum(h.count for h in hits)} replacements.',
        '',
    ])
    by_file: dict[Path, list[Hit]] = {}
    for h in hits:
        by_file.setdefault(h.path, []).append(h)
    if not by_file:
        lines.append('(no replacements needed)')
    for path, grp in sorted(by_file.items()):
        try:
            rel = path.relative_to(PROJECT_ROOT)
        except ValueError:
            rel = path
        lines.append(f'### `{rel}`')
        lines.append('')
        for h in grp:
            lines.append(f'- [pass {h.pass_num}] `{h.pattern}` -> `{h.replacement}` (x{h.count})')
        lines.append('')

    REPORT_PATH.write_text('\n'.join(lines), encoding='utf-8')
    print(f'wrote {REPORT_PATH}')
    print(f'files modified: {files_touched}')
    print(f'total replacements: {sum(h.count for h in hits)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
