#!/usr/bin/env python3
"""Write Phase G.7 bias-correction deliverable tables.

Produces (under ``tables/``):

  * table_4_bias_correction_summary.{csv,md,tex}    -- 8-row main table
  * S8_10_bias_correction_regimewise.{csv,md}       -- 80-row long-format
  * S8_11_bias_correction_form_b_stability.{csv,md} -- 40-row CV-reseed
    pass-through of the stability CSV.

All three are pure reads of existing Phase G.7 outputs; no models refit.
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.resolve()
os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd

from config import LOGS, RESULTS

TABLES_DIR = PROJECT_ROOT / 'tables'
LOG_PATH = LOGS / 'v10_phase_g_bias_correction_tables.log'

TRACK_LABEL = {'opx_liq': 'opx-liq', 'opx_only': 'opx-only',
               'cpx_liq': 'cpx-liq', 'cpx_only': 'cpx-only'}
UNIT = {'T_C': 'C', 'P_kbar': 'kbar'}


def _log(msg, fh):
    line = f'[{time.strftime("%Y-%m-%d %H:%M:%S")}] {msg}'
    print(line, flush=True)
    fh.write(line + '\n')
    fh.flush()


def _fmt(x, prec=2):
    try:
        fx = float(x)
    except (TypeError, ValueError):
        return '--'
    if not np.isfinite(fx):
        return '--'
    return f'{fx:.{prec}f}'


def _md_escape(s: str) -> str:
    return str(s).replace('|', '\\|')


def _write_md(path: Path, header: str, cols, rows):
    lines = [header, '']
    lines.append('| ' + ' | '.join(cols) + ' |')
    lines.append('|' + '|'.join(['---'] * len(cols)) + '|')
    for r in rows:
        lines.append('| ' + ' | '.join(_md_escape(x) for x in r) + ' |')
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def _write_tex(path: Path, caption: str, label: str, cols, rows):
    col_spec = 'l' * len(cols)
    lines = []
    lines.append('% Auto-generated by '
                 'scripts/v10_phase_g_bias_correction_tables.py')
    lines.append(r'\begin{table}[htbp]')
    lines.append(r'\centering')
    lines.append(r'\footnotesize')
    lines.append(r'\begin{tabular}{' + col_spec + '}')
    lines.append(r'\toprule')
    lines.append(' & '.join(str(c).replace('%', r'\%') for c in cols) + r' \\')
    lines.append(r'\midrule')
    for r in rows:
        lines.append(' & '.join(str(x).replace('%', r'\%') for x in r) + r' \\')
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\caption{' + caption + '}')
    lines.append(r'\label{' + label + '}')
    lines.append(r'\end{table}')
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def _pct_reduction(pre: float, post: float) -> float:
    if not np.isfinite(pre) or pre == 0 or not np.isfinite(post):
        return np.nan
    return 100.0 * (pre - post) / pre


def build_table_4(ship: pd.DataFrame, summ: pd.DataFrame,
                  pseed: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, r in ship.iterrows():
        track = r['track']; target = r['target']; winner = r['winner']
        pipe = r['pipeline']; model = r['model']; fset = r['feature_set']
        sa = summ[(summ.track == track) & (summ.target == target)
                  & (summ.form == 'A') & (summ.regime == 'ALL')]
        sb = summ[(summ.track == track) & (summ.target == target)
                  & (summ.form == 'B') & (summ.regime == 'ALL')]
        pre = float(sa['pre_rmse_mean'].iloc[0]) if not sa.empty else np.nan
        post_a = float(sa['post_rmse_mean'].iloc[0]) if not sa.empty else np.nan
        post_b = float(sb['post_rmse_mean'].iloc[0]) if not sb.empty else np.nan
        if winner == 'A':
            post = post_a
        elif winner == 'B':
            post = post_b
        else:
            post = np.nan
        delta = pre - post if np.isfinite(post) else np.nan
        pct = _pct_reduction(pre, post)
        ps_all = pseed[(pseed.track == track) & (pseed.target == target)
                       & (pseed.regime == 'ALL')].drop_duplicates(['seed'])
        n_tot = len(ps_all)
        n_a = int((ps_all.winner == 'A').sum())
        n_b = int((ps_all.winner == 'B').sum())
        n_none = int((~ps_all.winner.isin(['A', 'B'])).sum())
        rows.append({
            'pipeline': pipe,
            'track': TRACK_LABEL.get(track, track),
            'target': target,
            'model': f'{model}/{fset}',
            'shipped_form': winner,
            'pre_RMSE_test': pre,
            'post_RMSE_test': post,
            'delta_RMSE': delta,
            'pct_reduction': pct,
            'seed_vote': f'{n_a}/{n_b}/{n_none}',
            'n_seeds': n_tot,
        })
    return pd.DataFrame(rows)


def build_table_s8_10(summ: pd.DataFrame, pseed: pd.DataFrame,
                      ship: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, s in summ.sort_values(
            ['track', 'target', 'form', 'regime']).iterrows():
        track = s['track']; target = s['target']; form = s['form']; reg = s['regime']
        ps = pseed[(pseed.track == track) & (pseed.target == target)
                   & (pseed.form == form) & (pseed.regime == reg)]
        n = int(ps['n'].iloc[0]) if not ps.empty else 0
        pre_lo = ps['pre_lo'].mean() if not ps.empty else np.nan
        pre_hi = ps['pre_hi'].mean() if not ps.empty else np.nan
        post_lo = ps['post_lo'].mean() if not ps.empty else np.nan
        post_hi = ps['post_hi'].mean() if not ps.empty else np.nan
        pre_mean = float(s['pre_rmse_mean'])
        post_mean = float(s['post_rmse_mean'])
        delta = float(s['delta_rmse_mean'])
        sr = ship[(ship.track == track) & (ship.target == target)]
        winner = sr['winner'].iloc[0] if not sr.empty else 'none'
        ships = 'Y' if winner == form else 'N'
        rows.append({
            'pipeline': s['pipeline'],
            'track': TRACK_LABEL.get(track, track),
            'target': target,
            'regime': reg,
            'n': n,
            'form': form,
            'pre_RMSE_mean': pre_mean,
            'pre_RMSE_lo': pre_lo,
            'pre_RMSE_hi': pre_hi,
            'post_RMSE_mean': post_mean,
            'post_RMSE_lo': post_lo,
            'post_RMSE_hi': post_hi,
            'delta_RMSE': delta,
            'ships_cell': ships,
        })
    return pd.DataFrame(rows)


def build_table_s8_11(stab: pd.DataFrame) -> pd.DataFrame:
    out = stab.copy()
    out['track'] = out['track'].map(TRACK_LABEL).fillna(out['track'])
    cols = ['pipeline', 'track', 'target', 'model', 'feature_set',
            'model_seed', 'cv_seed', 'alpha_L', 'alpha_R',
            's_L', 's_R', 'oof_mse', 'form_b_ok']
    return out[cols]


def main():
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    fh = open(LOG_PATH, 'w', encoding='utf-8')
    try:
        ship = pd.read_csv(RESULTS / 'v10_bias_correction_shipped.csv')
        summ = pd.read_csv(RESULTS / 'v10_bias_correction_summary.csv')
        pseed = pd.read_csv(RESULTS / 'v10_bias_correction_per_seed.csv')
        stab = pd.read_csv(RESULTS / 'v10_bias_correction_form_b_stability.csv')

        # --- Table 4 (main) ---
        t4 = build_table_4(ship, summ, pseed)
        t4.to_csv(TABLES_DIR / 'table_4_bias_correction_summary.csv',
                  index=False)
        md_rows = []
        for _, r in t4.iterrows():
            unit = UNIT[r['target']]
            pre = _fmt(r['pre_RMSE_test'])
            post = (_fmt(r['post_RMSE_test'])
                    if np.isfinite(r['post_RMSE_test']) else '--')
            delta = (_fmt(r['delta_RMSE'])
                     if np.isfinite(r['delta_RMSE']) else '--')
            pct = (_fmt(r['pct_reduction'], 1) + '%'
                   if np.isfinite(r['pct_reduction']) else '--')
            md_rows.append([
                r['pipeline'], r['track'], r['target'], r['model'],
                r['shipped_form'],
                f'{pre} {unit}',
                f'{post} {unit}' if post != '--' else '--',
                f'{delta} {unit}' if delta != '--' else '--',
                pct,
                r['seed_vote'],
            ])
        cols_md = ['pipeline', 'track', 'target', 'model', 'shipped form',
                   'pre RMSE (test, ALL)', 'post RMSE (test, ALL)',
                   'delta RMSE', '% reduction', 'seed vote (A/B/none)']
        _write_md(TABLES_DIR / 'table_4_bias_correction_summary.md',
                  ('# Table 4: Phase G.7 bias-correction shipping summary\n\n'
                   'Canonical seed 42. 20-seed mean at regime=ALL; '
                   'delta = pre - post; positive delta means correction '
                   'improves test RMSE. Seed vote = number of seeds (of 20) '
                   'picking Form A / Form B / neither.'),
                  cols_md, md_rows)
        _write_tex(TABLES_DIR / 'table_4_bias_correction_summary.tex',
                   ('Phase G.7 bias-correction shipping summary. Canonical '
                    'seed 42. 20-seed mean at regime=ALL. Seed vote = '
                    'A/B/none over 20 model seeds.'),
                   'tab:bias_correction_summary', cols_md, md_rows)
        _log(f'wrote table_4: {len(t4)} rows', fh)

        # --- Table S8.10 (regime-wise) ---
        t10 = build_table_s8_10(summ, pseed, ship)
        t10.to_csv(TABLES_DIR / 'S8_10_bias_correction_regimewise.csv',
                   index=False)
        md_rows = []
        for _, r in t10.iterrows():
            unit = UNIT[r['target']]
            pre_ci = (f'{_fmt(r["pre_RMSE_mean"])} [{_fmt(r["pre_RMSE_lo"])}, '
                      f'{_fmt(r["pre_RMSE_hi"])}] {unit}')
            post_ci = (f'{_fmt(r["post_RMSE_mean"])} [{_fmt(r["post_RMSE_lo"])}, '
                       f'{_fmt(r["post_RMSE_hi"])}] {unit}')
            delta = f'{_fmt(r["delta_RMSE"])} {unit}'
            md_rows.append([
                r['pipeline'], r['track'], r['target'], r['regime'],
                r['n'], r['form'], pre_ci, post_ci, delta, r['ships_cell'],
            ])
        cols_md = ['pipeline', 'track', 'target', 'regime', 'n', 'form',
                   'pre RMSE [95% CI]', 'post RMSE [95% CI]', 'delta RMSE',
                   'cell ships?']
        _write_md(TABLES_DIR / 'S8_10_bias_correction_regimewise.md',
                  ('# Table S8.10: Phase G.7 bias-correction per-regime results\n\n'
                   'Each row is one regime x form for one cell. Pre/post RMSE '
                   'in native units at regime n. Bootstrap 95% CI averaged '
                   'across 20 seeds. Delta = pre - post (positive = '
                   'correction helps). `cell ships?` = Y when the '
                   'cell-level ship decision at canonical seed 42 selects '
                   'this form.'),
                  cols_md, md_rows)
        _log(f'wrote S8_10: {len(t10)} rows', fh)

        # --- Table S8.11 (Form B CV-reseed stability) ---
        t11 = build_table_s8_11(stab)
        t11.to_csv(TABLES_DIR / 'S8_11_bias_correction_form_b_stability.csv',
                   index=False)
        md_rows = []
        for _, r in t11.iterrows():
            md_rows.append([
                r['pipeline'], r['track'], r['target'], r['model'],
                r['feature_set'], r['model_seed'], r['cv_seed'],
                _fmt(r['alpha_L'], 3), _fmt(r['alpha_R'], 3),
                _fmt(r['s_L'], 3), _fmt(r['s_R'], 3),
                _fmt(r['oof_mse'], 2), str(r['form_b_ok']),
            ])
        cols_md = ['pipeline', 'track', 'target', 'model', 'feat.',
                   'model seed', 'CV seed',
                   'alpha_L', 'alpha_R', 's_L', 's_R', 'OOF MSE', 'Form B OK']
        _write_md(TABLES_DIR / 'S8_11_bias_correction_form_b_stability.md',
                  ('# Table S8.11: Form B parameter stability across 5 CV '
                   'reseeds\n\nForm B (quantile-thresholded piecewise) fit '
                   'parameters for each of the 8 Phase-G.7 cells at canonical '
                   'model seed 42 under five alternative '
                   'StratifiedGroupKFold split seeds. `Form B OK` is True '
                   'when the fit passed all validity checks (slope cap, '
                   'minimum middle-width, alpha ordering).'),
                  cols_md, md_rows)
        _log(f'wrote S8_11: {len(t11)} rows', fh)
        _log('DONE', fh)
        return 0
    finally:
        fh.close()


if __name__ == '__main__':
    sys.exit(main())
